server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index home.html;
        try_files $uri $uri/ /home.html;
    }

    location /socket.io/ {
        proxy_pass http://backend:5000/socket.io/;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend:5000/api/;
    }
}