services:
  backend:
    build: ./backend
    container_name: kahoot-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "--reload", "app:app"]

  frontend:
    image: nginx:alpine
    container_name: kahoot-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
