version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5000"  # accessible depuis Nginx
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:80"    # localhost:5000 -> Nginx
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
